name: Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: ['1.16', '1.17']
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: Run Tests for ${{ matrix.go }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
        - run: go test ./...
